name: Leafy Deployment

on: 
  pull_request:
    branches: [ master ]

jobs: 
  build_request:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn
      - run: tsc
      - run: pm2 restart 0